title: 양수영
description: 양수영의 포트폴리오
lang: ko-KR
timezone: Asia/Seoul
visitor_api_endpoint: "https://ysw-blog-visitor-counter.ysw1mst.workers.dev/visit"

url: "https://xn--9p4bn7dwj.com"
baseurl: ""

markdown: kramdown

plugins:
  - jekyll-seo-tag

exclude:
  - .bundle
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor
  - workers
